version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
      - ./src/modules/mail/templates:/app/src/modules/mail/templates

volumes:
  postgres_data: 